name: Deploy Cliente

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Branch base para criar a temporária'
        required: true
      cliente_ID:
        description: 'ID do cliente (nome do arquivo .properties)'
        required: true
      

env:
  cliente_id: fluighub${{ github.event.inputs.cliente_ID }}
  destino_branch: $cliente_id-prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o repositório
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # pega todo o histórico

    - name: Configurar Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Criar branch temporária
      run: |
        git fetch origin ${{ github.event.inputs.base_branch }}
        git checkout -b temp-$cliente_id origin/${{ github.event.inputs.base_branch }}

    - name: Copiar .properties da main
      run: |
        mkdir -p src/main/webapp/resources
        git fetch origin main
        git show origin/main:src/main/resources/configs/$cliente_id.properties > src/main/webapp/resources/config.properties

    - name: Fazer commit e push para destino
      run: |
        git add src/main/webapp/resources/config.properties
        git commit -m "Adiciona config.properties do cliente $cliente_id"
        git push origin temp-$cliente_id:$destino_branch

    - name: Apagar branch temporária local
      run: |
        git checkout $destino_branch
        git branch -D temp-$cliente_id

    - name: Apagar branch temporária remota (caso tenha sido criada)
      run: |
        git push origin --delete temp-$cliente_id || echo "Branch remota não existia"
