name: Criar branches versionadas para clientes

on:
  workflow_dispatch:  # permite rodar manualmente

jobs:
  create-client-release-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout completo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # necessário para buscar tags e todas as refs

      - name: Configura Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Obter última tag da main
        id: get_tag
        run: |
          TAG=$(git tag --sort=-creatordate | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          echo "Última TAG encontrada: $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Encontrar branches de cliente
        id: find_branches
        run: |
          git fetch --all
          git branch -r | grep 'origin/fluighub' | grep -v 'prod$' | sed 's/origin\/fluighub//' > branches.txt
          echo "Branches encontradas:"
          cat branches.txt
          echo "branches=$(cat branches.txt | paste -sd ',' -)" >> $GITHUB_OUTPUT

      - name: Criar novas branches versionadas para cada cliente
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          TAG: ${{ env.TAG }}
        run: |
          echo "Iniciando criação de branches versionadas com base na main..."
          git checkout main
          git pull origin main
          
          IFS=',' read -ra CLIENTS <<< "${{ steps.find_branches.outputs.branches }}"
          for CLIENT in "${CLIENTS[@]}"; do
            CLEAN_NAME=$(echo "$CLIENT" | xargs | sed 's/[^a-zA-Z0-9]//g')
            NEW_BRANCH="fluighub${CLEAN_NAME}-${TAG}"
            echo "Criando branch $NEW_BRANCH..."
            git checkout -b "$NEW_BRANCH" main
            git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} "$NEW_BRANCH"
          done
