# Este workflow é executado manualmente via interface do GitHub (workflow_dispatch) e recebe como input o nome de um cliente.
#
# Funcionalidade principal:
# 1. Recebe o nome de um cliente como input.
# 2. Cria duas novas branches no repositório com base na branch "main":
#    - Uma branch base para o cliente no formato: fluighub{cliente}
#    - Uma branch de produção no formato: fluighub{cliente}-prod
# 3. Faz push dessas branches para o repositório remoto.
#
# Esse processo automatiza a preparação da estrutura de branches para novos clientes,
# seguindo um padrão de versionamento baseado na branch principal (main).

name: Criar Branches base de Cliente

on:
  workflow_dispatch:
    inputs:
      cliente:
        description: 'Nome do cliente (ex: sebraern)'
        required: true

jobs:
  create-branches:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Definir variáveis e criar branches
      run: |
        CLIENTE=${{ github.event.inputs.cliente }}  # Recebe a variável CLIENTE
        BASE="fluighub"
        CLIENTE="${BASE}${CLIENTE}"  # Cria o nome da branch do cliente
        RELEASE="main"
        
        echo "Cliente: $CLIENTE"
        echo "Base: $BASE"
        echo "Release: $RELEASE"

        # Cria branch do cliente baseada em versão
        git checkout $RELEASE
        git pull origin $RELEASE
        git checkout -b $CLIENTE
        git push origin $CLIENTE

        # Cria a branch de produção
        git checkout -b "$CLIENTE-prod"
        git push origin "$CLIENTE-prod"
        
        echo "Branches criadas: $CLIENTE e $CLIENTE-prod"
