name: Criar branch release da main

on:
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # precisa para buscar tags

      - name: Pega a última tag (versão atual da main)
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Cria nova branch de release baseada na main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          VERSION=${{ steps.get_tag.outputs.TAG }}
          RELEASE_BRANCH="release/$VERSION"
          
          # Cria a branch a partir da main
          git checkout main
          git pull origin main
          git checkout -b $RELEASE_BRANCH
          git push origin $RELEASE_BRANCH
