# Este workflow é acionado manualmente (via workflow_dispatch) ou automaticamente 
# quando um Pull Request é fechado na branch "main" e foi mesclado com sucesso.
# Ele executa os seguintes passos:
# 1. Faz checkout completo do repositório (incluindo tags).
# 2. Recupera a última tag (versão atual da main).
# 3. Cria uma nova branch de release chamada "release/{tag}" baseada na main.
# 4. Faz push dessa nova branch para o repositório remoto.
# Esse processo automatiza a criação de branches de release após a finalização de PRs na main.

name: Cria branch release da main

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-release-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # precisa para buscar tags

      - name: Pega a última tag (versão atual da main)
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Cria nova branch de release baseada na main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          VERSION=${{ steps.get_tag.outputs.TAG }}
          RELEASE_BRANCH="release/$VERSION"
          
          # Cria a branch a partir da main
          git checkout main
          git pull origin main
          git checkout -b $RELEASE_BRANCH
          git push origin $RELEASE_BRANCH
